 # Throw

Demonstrates throwing an error (and then catching it with the try/catch block)
